name: pulsebridge-app publish

on:
  push:
    tags:
      - v*.*.*

env:
  ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
  ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
  ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
  ANDROID_KEYSTORE_PATH: ${{ secrets.ANDROID_KEYSTORE_PATH }}
jobs:
  deploy:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: android-actions/setup-android@v3
      - run: yes | sdkmanager 'platforms;android-33'

      #FDROID FASTLANE METADATA VALIDATION
      - name: Validate Fastlane Supply Metadata
        uses: ashutoshgngwr/validate-fastlane-supply-metadata@v2

    #  - name: Decrypt keystore
    #    run: openssl aes-256-cbc -K ${{ secrets.ANDROID_KEYSTORE_SSL_KEY }} -iv ${{ secrets.ANDROID_KEYSTORE_SSL_IV }} -in pulsebridge.jks.enc -out pulsebridge.jks -d
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - run: make assemble-release
      - name: Build Release AAB
        run: ./gradlew bundleGenericRelease
      - name: Build Release APK
        run: ./gradlew assembleGenericRelease
      - name: Sign AAB with Jarsigner
        run: |
          # If your keypass is different from storepass, you'll need ANDROID_KEY_PASSWORD secret for it.
          jarsigner -keystore "${{ env.ANDROID_KEYSTORE_PATH }}" --storepass "${{ env.ANDROID_KEYSTORE_PASSWORD }}" ./build/outputs/bundle/genericRelease/*.aab key0
      - name: Sign AAB with Jarsigner
        run: |
          # If your keypass is different from storepass, you'll need ANDROID_KEY_PASSWORD secret for it.
          jarsigner -keystore "${{ env.ANDROID_KEYSTORE_PATH }}" --storepass "${{ env.ANDROID_KEYSTORE_PASSWORD }}" ./build/outputs/apk/generic/release/*.apk key0
        env:
          GIT_TAG: ${{ github.ref_name }}
      - name: GitHub release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          files: |
            ./build/outputs/apk/**/release/*.apk
            ./build/outputs/bundle/genericRelease/*.aab
